apiVersion: v1
kind: Service
metadata:
  name: xerxes-website-service
  labels:
    app: xerxes-website
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: xerxes-website 